### ISSUE TITLE
Add support for checking value-object arrays when generating equals 

### ISSUE THREAD

**Issue by punkstar** [Space48/auto-value-php#7]
Consider the following, where an `Order` can have a number of `Shipment` value-objects associated with it:

```php
/**
 * @AutoValue
 */
abstract class Shipment
{
    /**
     * @param string $value
     * @return Shipment
     */
    abstract public function withTrackingNumber(string $value): self;

    /**
     * @return string
     */
    abstract public function getTrackingNumber(): string;
    
    abstract public function equals($value): bool;
}

/**
 * @AutoValue
 */
abstract class Order
{
    /**
     * @param Shipment[] $values
     * @return Order
     */
    abstract public function withShipments(array $values): self;

    /**
     * @return Shipment[]
     */
    abstract public function getShipments(): array;

    abstract public function equals($value): bool;
}
```
When calling `$order->equals($anotherOrder)` it would be nice to offload the equality check of the shipments array to the `Shipment` class where it has its own implementation of `equals`.

As I understand it, the generated `AutoValue_Order` class will currently perform the array equality check, an `array_udiff_assoc`, on the order's shipments. It would be really useful it this could instead use the `equals` method on the `Shipment` to establish equality.

**Comment by joshdifabio** [comment]
This should already be happening -- but perhaps it's broken. Could you upload the generated Order and Shipment code somewhere?

**Comment by punkstar** [comment]
How did I miss that. I see the `method_exists` check for `equals` now.

**Comment by punkstar** [comment]
The only way that the way the existing implementation is tripping me up is because I don't care about the order of the Shipments on the Order. If there are two shipments attached to the order and they are equal to each other, I don't care whether shipment 1 is first in the array or if shipment 2 is.

I'm going to go with a custom implementation of `equals` to cover off this scenario in my work. I have a suspicion that it may be a common scenario though so may warrant the addition of some configuration annotations to `equals`?

**Comment by joshdifabio** [comment]
Custom `equals()` is the best way for now. The best way to handle this long term is probably to create a data structure like Java's `Set` which has its own `equals` method which ignores ordering of elements. I'm already in progress with some immutable data structures to solve this kind of thing so I'll try and get them on GitHub in the next couple of weeks.
